site_name: WordPressPCL
site_url: https://wp-net.github.io/WordPressPCL/
nav:
    - Home: index.md
    - Version 2.x:
        - Getting Started: v2/getting-started.md
        - Types:
            - Comments: v2/types/comments.md
    - Version 1.x:
        - Types:
            - Comments: v1/types/comments.md
            - Posts: v1/types/posts.md


theme: readthedocs