version: "3.9"

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  
  wordpress:
    depends_on:
      - db
    build:
      context: .
    image: wordpress-custom
    volumes:
      - wp-volume:/var/www/html
    ports:
      - "8080:80"
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
      WORDPRESS_CONFIG_EXTRA: define('JWT_AUTH_SECRET_KEY', '.|)WaUppb-a>Z;(%p,4~^|5jjWom6Gw{(2_lqJv9r&]p<r4=rAvjM(LepuRf&+wI');
  
  cli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    user: xfs
    container_name: wp-cli
    volumes:
      - wp-volume:/var/www/html
    env_file:
      - .env
    command: >
      /bin/sh -c '
      sleep 10;
      wp core install --path="/var/www/html" --url="http://localhost:8080" --title="Test Instance" --admin_user=wordpress --admin_password=wordpress --admin_email=test@example.com;
      wp option update permalink_structure "/%postname%";
      wp plugin activate "enable-application-passwords.1.0";
      wp plugin install contact-form-7 --activate;
      wp plugin install jwt-authentication-for-wp-rest-api --activate;'
      
volumes: 
  wp-volume:

networks:
  default:
    name: integration-tests-setup